### ISSUE TITLE
Update supported Python versions

### ISSUE THREAD

**Issue by jugmac00** [morepath/more.static#13]
- drop support for Python versions < 3.6
- add support for Python versions 3.7, 3.8 (if missing)
- fix linting errors (if present)

If you are a beginner, and need to help for this issue, especially during Hacktoberfest, please comment here or reach out to me via https://jugmac00.github.io/

**Comment by sgaist** [comment]
Hi,

I'd like to do this one.

**Comment by jugmac00** [comment]
Go for it. Hacktoberfest already started!

**Comment by jugmac00** [comment]
A similar issue was solved just a couple of minutes ago
https://github.com/morepath/morepath_static/pull/4/files

Though, here we have one more problem, see #12  - for that one I have no solution yet - I guess this needs some "googling" :-)
